### ISSUE TITLE
using int instead of int32 when calling Raylib functions?

### ISSUE THREAD

**Issue by X-Ninja-dev** [planetis-m/naylib#102]
This is a general Nim question and not specific to Naylib so feel free to delete and send me to the forums instead

Using a tuple in the code I have to declare the values as int32, why is that? And is there a way to tell the compiler to use  int32?
```nim
import raylib
const
  screenW = 800
  screenH = 600
  screenSize = (x: 800, y: 600)

proc main(): void =
  # works
  initWindow(screenW, screenH, "testing")

  # does not work. Error: type mismatch
  initWindow(screenSize.x, screenSize.y, "testing")

main()
```

**Comment by planetis-m** [comment]
No idea really, const implicit types buffle me as well.
