### ISSUE TITLE
Support the msvc compiler.

### ISSUE THREAD

**Issue by ethindp** [planetis-m/naylib#104]
On Windows, using `-cc=vcc` fails because GNU-style arguments are being passed to `cl.exe`. This can be resolved by using `-cc=clang`, but this causes a compilation error in GLFW because types like `WINBOOL` aren't defined, leading to a misleading syntax error:

```
naylib-5.0.2-9979f2e337750d00c4e9feeb34641600f83dd86b\raylib\src\external\glfw\deps\mingw\xinput.h:227:26: error:
      a parameter list without types is only allowed in a function definition
  227 | void WINAPI XInputEnable(WINBOOL);
      |                          ^
1 error generated.
```

If the compiler can be determined, the best solution would be to just pull in the windows headers on a windows target and assume that the user is building with MSVC (most users will probably go this route, MinGW/MSys2 doesn't exactly work well on Windows these days particularly with security mitigations enabled).

**Comment by planetis-m** [comment]
No, the official way to install Nim is to use MinGW. Try winlibs.com Unfortunately I cannot help you fix this, as I don't own a windows machine.

**Comment by planetis-m** [comment]
You need to turn off the bullshit security mitigations by MS by putting the mingw directories to a whitelist. Since there's no response to call for help closing.
