### ISSUE TITLE
Thoughts on raygui?

### ISSUE THREAD

**Issue by Niminem** [planetis-m/naylib#109]
Thoughts on including raygui module?

**Comment by planetis-m** [comment]
Not gonna happen. Check the repo naygui or naylibgui.

**Comment by planetis-m** [comment]
OK this has been brought up a couple of times and beside

**Comment by Niminem** [comment]
Booooooooooooooooooooooooo!

**Comment by planetis-m** [comment]
I am waiting for a PR for integrating this crappy C module.

**Comment by planetis-m** [comment]
Rewritten in nim only.
