### ISSUE TITLE
override config.h / enable SVG

### ISSUE THREAD

**Issue by mdos98** [planetis-m/naylib#110]
how can I enable `SUPPORT_FILEFORMAT_SVG`

thanks in advance.

**Comment by planetis-m** [comment]
It's very easy, you need to add a passC pragma with your define like [this](https://github.com/planetis-m/raylib-examples/blob/main/core/custom_frame_control.nim) example. Bare in mind that I have tested svg support in raylib and it's in a bad state.

**Comment by mdos98** [comment]
thank you
