### ISSUE TITLE
Plan to rewrite the generator scripts.

### ISSUE THREAD

**Issue by planetis-m** [planetis-m/naylib#111]
The scripts that are used to generate the wrapper have grown in complexity and are difficult to understand and modify. Experience has shown that trying to modify the produced nim code from a representation like, json, xml, etc, that the generators are using, leads to horrible, unmaintanable code. This is better done at the nim AST level. So to evolve the scripts, keep the maintenance cost down, make them easily extensive, the two separate tasks of parsing the C header definitions and outputting bindings, and making an idiomatic nim wrapper based on those bindings, should use two different programs. The bindings parser, can use the raylib_parser for a start, or eventually be ported to c2nim/furthark. It doesn't attempt to do any transformations and use the c types. This is necessary as upstream will not improve it to parse other headers than raylib.h correctly, it half works with rlgl.h and requires manual intervention. Another program the wrapper generator, makes use of the compiler as a library, and parses the bindings it traverses the nim ast and writes our wrapper in a file.

**Comment by planetis-m** [comment]
mwe for the second program:

```nim
import
  compiler/[ast, parser, idents, astalgo, pathutils, condsyms, renderer,
  options, nimconf, extccomp, modulegraphs],
  std/os

# need ./koch checksums

proc traverse(node: PNode) =
  case node.kind
  of nkImportStmt:
    echo "Import statement: ", node.repr
  of nkProcDef:
    echo "Procedure definition: ", node.repr
  of nkVarSection:
    echo "Variable declaration: ", node.repr
  else:
    echo "Other node: ", node.repr
  for child in node.items:
    traverse(child)

proc main =
  # Create a new configuration and module graph
  var conf = newConfigRef()
  var cache = newIdentCache()
  var graph = newModuleGraph(cache, conf)
  # Initialize defines and load configurations
  condsyms.initDefines(conf.symbols)
  conf.projectName = "stdinfile"
  conf.projectFull = "stdinfile".AbsoluteFile
  conf.projectPath = canonicalizePath(conf, getCurrentDir().AbsoluteFile).AbsoluteDir
  conf.projectIsStdin = true
  loadConfigs(DefaultConfig, cache, conf, graph.idgen)
  # Initialize external compiler variables
  extccomp.initVars(conf)
  # Parse input file and traverse the AST
  let inputFile = "input.nim"
  let node = parseString(readFile(inputFile), cache, conf)
  node.traverse()
  # Render the module to an output file
  let outputFile = "output.nim"
  renderModule(node, outputFile, {renderDocComments})

main()
```

**Comment by planetis-m** [comment]
Something similar was done in https://github.com/nim-lang/c2nim/blob/araq-gobject/gobject2nim.nim

**Comment by planetis-m** [comment]
I am ignoring the easiest solution, to add it as a macro instead: https://github.com/nim-lang/opengl/blob/master/src/opengl/private/errors.nim There're helpful macros for this purpose as well: https://github.com/geekrelief/genit

**Comment by Xkonti** [comment]
It's great that you're documenting the progress here via issues!

**Comment by planetis-m** [comment]
Nah waste of time, instead the existing scripts were refactored.
