### ISSUE TITLE
[please ignore warning] Incorrect package structure - import file named raylib.nim instead of naylib.nim

### ISSUE THREAD

**Issue by Doublestuf** [planetis-m/naylib#123]
Installing the package with nimble causes a warning:
"Warning: Package 'naylib' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'naylib.nim', but a file named 'raylib.nim' was found. This will be an error in the future."

Caused me some trouble, struggled for about an hour trying to see why `import naylib` wasn't working before looking into the .nimble directory and trying to import raylib.nim. Likely impacted by me being new to Nim, but worth changing to prevent a nimble error.

**Comment by planetis-m** [comment]
Sorry for the confusion, I'll see what can be done to silence the warning.

**Comment by planetis-m** [comment]
Finally the warning was [removed](https://github.com/nim-lang/nimble/pull/1236) however it may take a while until a new nimble version ships. Keeping it pinned fir visibility.
