### ISSUE TITLE
Webassembly compilation errors

### ISSUE THREAD

**Issue by Doublestuf** [planetis-m/naylib#125]
Followed the instructions in the README, I have emscripten installed.
Using `nim c -d:emscripten main.nim` results in
```
CC: rshapes
Error: invocation of external compiler program failed. The system cannot find the file specified.
```
Using the command `nim js -d:emscripten main.nim` results in `.nimble\pkgs2\naylib-5.1.2-575dd0808efc4134c50d71e2596fa13a9ecc9cb4\raylib.nim(1701, 1) Error: signature for '=destroy' must be proc[T: object](x: var T).`

**Comment by planetis-m** [comment]
Are you using nim v1? The signature for destroy was changed in v2 https://nim-lang.org/blog/2023/08/01/nim-v20-released.html

**Comment by planetis-m** [comment]
And also make sure you're on naylib v5.1.3 released today.

**Comment by planetis-m** [comment]
It was an issue with the rename of platforms/rcore_desktop.c to rcore_desktop_glfw.c in upstream raylib 5.5. I fixed it today.

**Comment by Doublestuf** [comment]
Updated to Naylib 5.1.3, same result. I'm on Nim 2.0.8. Only difference I can see is that the second error is now on line 1721 of raylib.nim.

**Comment by planetis-m** [comment]
> Updated to Naylib 5.1.3, same result. I'm on Nim 2.0.8. Only difference I can see is that the second error is now on line 1721 of raylib.nim.

The correct command is `nim c -d:emscripten main.nim` not `nim js`

**Comment by Doublestuf** [comment]
Seems to be an issue with emscripten, `emcc.bat command not found`, will try to fix there.

**Comment by planetis-m** [comment]
I al assuming you have properly installed emscripten since then, right? https://emscripten.org/docs/getting_started/downloads.html
