### ISSUE TITLE
Trouble with glTF animations.

### ISSUE THREAD

**Issue by coderextreme** [planetis-m/naylib#140]
See attached glTF.

Here's the code that fails:

let anims: RArray[ModelAnimation] = loadModelAnimations("resources/JoeSkinTexcoordDisplacerKickUpdate2Export.gltf")
let a = anims[0]
[Joe.zip](https://github.com/user-attachments/files/17486437/Joe.zip)

**Comment by planetis-m** [comment]
I think we solved that issue on discord
