### ISSUE TITLE
Why is there a hole in my sphere?

### ISSUE THREAD

**Issue by coderextreme** [planetis-m/naylib#141]
Hole in sphere mesh?  Why?

Thanks!
[hole.zip](https://github.com/user-attachments/files/17493956/hole.zip)

**Comment by planetis-m** [comment]
The sphere is clipped because it intersects with the camera plane, I guess?

**Comment by coderextreme** [comment]
When I reduce the number of subdivisions (slices and the other parameter),
the hole goes away.
