### ISSUE TITLE
'atlas' installation messes up files

### ISSUE THREAD

**Issue by matkuki** [planetis-m/naylib#146]
Hi,

Specs:
- Windows 10 x64
- Nim: little behing devel
- Atlas: compiled from source

Running:
> atlas init
> atlas use "https://github.com/planetis-m/naylib"

causes the git repo for `naylib` in the dependencies directory to get messed up. It looks like the `after install` hook does something wrong, but that is my guess.

**Comment by planetis-m** [comment]
What's exactly wrong with it? AFAIK with atlas it should run the branch:

after install:
  when defined(atlas):
    localInstallTask()
    
The localInstallTask is tested by the CI:

task test, "Runs the test suite":
  localInstallTask()
  
And the other branch is also taken by the examples CI which installs naylib as a dependency.

**Comment by planetis-m** [comment]
It could be an issue with path handling. It needs to use quoteShell somewhere.

Can you open raylib.nim in your installation and post the `raylibDir` constant in the 5th line?

**Comment by planetis-m** [comment]
I tried to install in a path that has spaces but atlas doesn't even run correctly. If your path is irregular report the issue to atlas.

**Comment by matkuki** [comment]
My project path: `E:\Nim\naylib\text_editor`

5th line in `raylib.nim`:
```nim
const raylibDir = Path(r"E:\Nim\naylib\text_editor\dependencies\naylib\src\raylib")
```

**Comment by planetis-m** [comment]
Seems ok? And what's the error?

**Comment by matkuki** [comment]
One thing is, the entire `src/raylib` subdirectory is missing. This is what is in the `atlas` installed `src` directory:
![image](https://github.com/user-attachments/assets/7fa6d2ea-6db1-496a-9115-8404a4ea3c2b)
... and this is what is in the `nimble` installed package:
![image](https://github.com/user-attachments/assets/86d719bb-d8ae-4ee1-80e3-812260cbe8b0)
And the git log of the `atlas` repo shows this (TortoiseGit):
![image](https://github.com/user-attachments/assets/20b73dd9-05a1-4603-ae76-6321c7b9418d)
I didn't do anything in any of the directories, this is just after `atlas use ...`.

**Comment by planetis-m** [comment]
So atlas decided to do silly things like nimble...

**Comment by matkuki** [comment]
Had the same thing happened when installing `sdl2` with `atlas`. Reported this to `atlas` repo: https://github.com/nim-lang/atlas/issues/135
