### ISSUE TITLE
Docs site search box doesn't work

### ISSUE THREAD

**Issue by optik-aper** [planetis-m/naylib#31]
The search box on the docs site doesn't work.  The browser console shows:

```
Loading failed for the <script> with source “https://planetis-m.github.io/naylib/dochack.js”.
Uncaught ReferenceError: search is not defined
    onkeyup https://planetis-m.github.io/naylib/raylib.html:1
```
The file `dockhack.js` 404s when visited in the browser.

**Comment by planetis-m** [comment]
This is an issue with the doc command for now I included dochack.js from another project.

**Comment by planetis-m** [comment]
Needs --project to work properly.

**Comment by planetis-m** [comment]
Can't make it work, raylib and raymath shouldn't depend on each other, just added separate links in the readme.
