### ISSUE TITLE
Missing nakefile in Nimble path

### ISSUE THREAD

**Issue by optik-aper** [planetis-m/naylib#32]
The instructions for installation using nimble appear to be missing a step:
```
cd $(nimble path naylib)
nake buildDesktop
No nakefile.nim found. Current working dir is /home/michael/.nimble/pkgs/naylib-1.6.0
```
The files in the naylib nimble directory:
```
naylib.nimble  nimblemeta.json  raylib.nim  raymath.nim
```

os: Ubuntu 20.04
version: 1.6.0 installed via `nimble install` with naylib in `requires`

**Comment by planetis-m** [comment]
nimble removes stuff it shouldn't. I asked for help but I don't know how to fix this.

**Comment by planetis-m** [comment]
Sorry won't fix, get a better package manager than this crap.

**Comment by planetis-m** [comment]
Ideally for nimble a hybrid package could be created (and that was attempted before in https://github.com/planetis-m/naylib/commit/70c1600a20998354ac3fd40e2204af765a028321). Then you would call `nayget myproject` and it would fork the the naylib-template (not done yet). It would also clone raysan5/raylib and create a shared lib and the appropriate .nims to correctly link it. However that work met some obstacles. For one I couldn't make ``--passL: incldir / "include"`` work inside a .nims file. Compiler bugs and nimble being a total PITA, with the nimble author refusing to admit any mistake, make me not want to try to fix this. I am really sorry.

**Comment by planetis-m** [comment]
Fixed but if I want to support the thing described above, I will have to break everything again.
