### ISSUE TITLE
Deal with cstring parameters

### ISSUE THREAD

**Issue by planetis-m** [planetis-m/naylib#5]

**Comment by planetis-m** [comment]
Left: initWindow, setWindowTitle, setClipboardText, getShaderLocation, getShaderLocationAttrib, takeScreenshot, traceLog, setGamepadMappings, loadImageAnim, exportImage, exportImageAsCode, genImageText, imageText, imageDrawText, exportFontAsCode, drawText, measureText, exportMesh, exportWave, exportWaveAsCode. Needs to be done automatically else don't do it at all.

**Comment by actondev** [comment]
What is the idea for cstrings? I just found myself editing the drawTextEx for raylib to pass the size, so that (from nim side) you can use `openArray[char]`, and call the raylib api by converting it to `cstring` (casting the openArray's `[0].addr`) and passing as well its `.len`.

**Comment by planetis-m** [comment]
Γεια σου φιλε Χρήστο,

I agree that calling `TextLength` when we are already know the size is not optimal, and it's also problematic for strings that contain `\0` before the end. But nim's string type has a (non-retrievable) ending \0 for compatibility reasons with C. If you need to use another string type, then you did good to open a ticket in raylib. But I don't have high hopes that Ray will consider it, although it makes a lot of sense for many other languages as well.

**Comment by actondev** [comment]
Oh, was assuming I'd have to copy to obtain a null-terminated one. Thanks!

**Comment by planetis-m** [comment]
Dealt with.
