### ISSUE TITLE
Naylib requires a Nim version that is not out yet

### ISSUE THREAD

**Issue by rivten** [planetis-m/naylib#52]
When I do `nimble install naylib`, I get the error : `Error: Unsatisfied dependency: nim (>= 1.9.1)`. But from the `nim` release page, it seems that the most recent version is 1.6.10. https://github.com/nim-lang/Nim/tags

I guess this is a typo ?

Happy christmas !!!!

**Comment by planetis-m** [comment]
Not a typo, it needs [nim 2.0 rc](https://nim-lang.org/blog/2022/12/21/version-20-rc.html) to compile. 

Happy Christmas hugo!

**Comment by rivten** [comment]
Ah ! Did not think of that !
