### ISSUE TITLE
Plan for wrapping raygui & rres

### ISSUE THREAD

**Issue by rishavs** [planetis-m/naylib#59]
Hi

Is there a plan for wrapping rres & raygui.

**Comment by planetis-m** [comment]
Hi thanks for dropping by. What's your use case? And how do you plan to help the project, if you don't mind me asking?

**Comment by rishavs** [comment]
Hi @planetis-m 
right now, I am evaluating which of the raylib bindings to use - rres and raygui wrappers being among my criteria. 

I wouldn't be able to contribute to the project atm. But once I have started using the library in my projects, I can help out with some of the smaller tasks like docs, examples etc.

**Comment by planetis-m** [comment]
Actually neither of them are a part of raylib. You can run c2nim and obtain bindings quite easily. The project is already tough to maintain as is and that would add a ton more work for one person. Examples are not part of this project either. If you don't plan on contributing said bindings, considering a financial contribution.

**Comment by ryback08** [comment]
Hello, 

I began to wrapp RayGui.
You can find the project here : https://github.com/ryback08/naylibgui
 
Hobbyst, i'm interesset in your feedback about good practice on nim.

**Comment by planetis-m** [comment]
@ryback08 I have made an effort myself at planetis-m/naygui but I realized that creating an idiomatic wrapper from raygui is kind of difficult.
