### ISSUE TITLE
Prevent double-free errors when user accidentally calls unload* 

### ISSUE THREAD

**Issue by planetis-m** [planetis-m/naylib#61]
This library uses destructors, so the unload* procs shouldn't be exposed. Reason is that they don't null the pointers. Only reset(x) does. Except unloadModelKeepMeshes, this should be kept and pbl wrapped to call x = default(T) afterwards.

**Comment by VaguinerG** [comment]
Excuse me, but how do I unload a texture? There are situations where it won't be reused ever again, but it seems that the compiler doesn't know that, and as a result it is stored all the time.

**Comment by planetis-m** [comment]
As the issue says with reset. Or you can take advantage that memory management is scope based and limit the variables scope.
