### ISSUE TITLE
wrong version number dependency?

### ISSUE THREAD

**Issue by waotzi** [planetis-m/naylib#63]
how come it says this in the nimble file?

requires "nim >= 1.9.1"

as far as i can tell the latest version of nim 1.6.10, trying to install the package using nimble gives an error

**Comment by planetis-m** [comment]
Sorry this question comes up once in a while and I should pbl write it in the readme. But this library uses destructors and other language features that are not available in v1.6. That doesn't mean though it can't be ported to it, just none contributed it. I hope v2 gets released soon (at least that's what the intend of the devs was last time I asked) but in the meantime please use https://github.com/nim-lang/nightlies/releases

**Comment by waotzi** [comment]
thank you, that works!
