### ISSUE TITLE
emscripten/emscripten.h: No such file or directory

### ISSUE THREAD

**Issue by waotzi** [planetis-m/naylib#67]
Hey i get the following issue when i try to build for web:

````sh
/home/wao/.nimble/pkgs/naylib-1.12.0/raylib/src/rcore.c:297:14: fatal error: emscripten/emscripten.h: No such file or directory
297 |     #include <emscripten/emscripten.h>  // Emscripten functionality for C
|              ^~~~~~~~~~~~~
````

do you know what i could try doing differently? is it possible to directly specify the emsdk/upstream/emscripten folder in the build directly?

**Comment by planetis-m** [comment]
Yes possibly. By setting the clang.path/clang.cpp.path options to the emscripten directory and passC: "-I" in the config file. Warning not tested:

```
const AndroidToolchain = "/opt/emscripten-llvm/"
switch("clang.path", EmscriptenToolchain / "bin")
switch("clang.cpp.path", EmscriptenToolchain / "bin")
switch("passC", "/usr/lib/emscripten/system/include/emscripten/")
```
