### ISSUE TITLE
Use concepts for drop-in vectors

### ISSUE THREAD

**Issue by beef331** [planetis-m/naylib#72]
Instead of the present state if you want to support other libraries you could do something like
```nim
type
  Vect2 = concept v
    v.x is float32
    v.y is float32

**Comment by planetis-m** [comment]
I wish that was possible. Anyway thanks for confirming I'm not totally insane.

**Comment by beef331** [comment]
Well it's possible one way, the otherway is not really, though a template could exist like `template emitConverter(T: typedesc[Vec2])  = ...`
