### ISSUE TITLE
No way to generate Mesh?

### ISSUE THREAD

**Issue by thefakeplace** [planetis-m/naylib#88]
Looking at the source, it doesn't seem possible to create a mesh.

Pattern from Raylib (C):
```c
// Generate a simple triangle mesh from code
static Mesh GenMeshCustom(void)
{
    Mesh mesh = { 0 };
    mesh.triangleCount = 1;
    mesh.vertexCount = mesh.triangleCount*3;
    mesh.vertices = (float *)MemAlloc(mesh.vertexCount*3*sizeof(float));    // 3 vertices, 3 coordinates each (x, y, z)
    mesh.texcoords = (float *)MemAlloc(mesh.vertexCount*2*sizeof(float));   // 3 vertices, 2 coordinates each (x, y)
    mesh.normals = (float *)MemAlloc(mesh.vertexCount*3*sizeof(float));     // 3 vertices, 3 coordinates each (x, y, z)

    /* ... */
}
```

I can't figure out how to do this in Naylib, am I reading the source wrong?

**Comment by planetis-m** [comment]
I can't provide a code sample right now but https://nim-lang.github.io/Nim/importutils.html#privateAccess%2Ctypedesc was tested before and it works. As for getting MemAlloc, you need to importc it in your project (just copy the definition found in raylib.nim).

**Comment by planetis-m** [comment]
see example [models/mesh_generation.nim](https://github.com/planetis-m/raylib-examples/tree/main/models/mesh_generation.nim)

**Comment by planetis-m** [comment]
see example [models/mesh_generation.nim](https://github.com/planetis-m/raylib-examples/tree/main/models/mesh_generation.nim)

**Comment by planetis-m** [comment]
see example [models/mesh_generation.nim](https://github.com/planetis-m/raylib-examples/tree/main/models/mesh_generation.nim)
