### ISSUE TITLE
Calling reset on an Image breaks compilation on Windows

### ISSUE THREAD

**Issue by jehoz** [planetis-m/naylib#90]
Not sure if this is the case for other data types as well, but it seems like calling `reset` on an Image variable (like in the [heightmap example](https://github.com/planetis-m/raylib-examples/blob/main/models/heightmap.nim#L47)) causes a bunch of  `conflicting types for '...'` errors (I am guessing because of some naming conflicts between raylib.h and windows.h that weren't caught by the mangle_names patch?)
If I take that line out of of the example it compiles and runs just fine.

I tried to investigate more, but I'm still pretty new to both raylib and nim in general so it might be a little over my head.
I see that the normal `=destroy` destructor for Images just calls `unloadImage`, is `reset` doing something else here?

**Comment by planetis-m** [comment]
I am assuming these are the same errors as posted in #89

**Comment by jehoz** [comment]
Yep, looks like the same ones!
Sorry, didn't realize there was already an issue with the same errors.
